# -*- coding: utf-8 -*-
"""Assignment 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vVJs3dKIV9GUZ2fa88om1J8YERi1kR1_
"""

#### PYTHON COURSE FOR BEGINNERS ####
# Week 1
# ID: 211877873
# Name: Manar Khalaila


# 1. Create Variables

participant_ids = [1, 2, 3, 4, 5, 6]
gender = ["female", "male", "female", "male", "female", "male"]
age = [23, 30, 19, 27, 25, 29]
depression_scores = [0, 1, 0, 1, 0, 1]


# 2. Create DataFrame

import pandas as pd

df = pd.DataFrame({
    "participant_num": participant_ids,
    "gender": gender,
    "age": age,
    "depression": depression_scores
})


# 3. Save to CSV

df.to_csv("week1_assignment.csv", index=False)
print("Week 1 assignment dataframe:")
print(df)
